<?php
include "registrar_articulo.html";
include "editar_articulo.html";
include "filtrar_articulo.html";
include "detalle_articulo.html";
include "registrar_entrada.html";
include "detalle_entrada.html";
include "editar_movimiento.html";
include "detalle_transacciones.html";
include "catalogos.html";
include "registrar_requisicion.html";
include "editar_requisicion.html";
include "detalle_requisicion.html";
include "surtir_requisicion.html";
include "detalle_surtimiento.html";
include "registrar_entrada_estable.html";
include "detalle_entrada_estable.html";
include "editar_entrada_estable.html";
include "registrar_entrada_orden_estable.html";